### PR TITLE
Jhz

### PR DESCRIPTION
**Pull request by jinghuazhao**
I started from my branch now.

### CODE REVIEW

**Comment by jinghuazhao** [comment]
Looks OK.

**Comment by remlapmot** [comment]
I think you closed this by accident, so will reopen,

**Comment by jinghuazhao** [comment]
It says "All checks have passed" but not sure I need do anything?

**Comment by explodecomputer** [comment]
Brilliant thank you, much appreciated

**Comment by jinghuazhao** [comment]
This is nothing to do with the pull request -- I realised that index.md is not really need since README.md will be made into index.html by pkgdown. It also looks neater (a personal taste maybe) to have _pkgdown.yml in pkgdown/ directory giving the possibility that other files could also be deposited there.

**Pull request merged**
