### PR TITLE
Revisions on NAMESPACE and read_data.R

### PR DESCRIPTION
**Pull request by jinghuazhao**
My colleague tried to use GWAS sumstats with only OR and P values; the get_se() was very useful but was not exported. I revised this in a minor version to be used locally and you are welcome to pull it/make changes yourself. 

I also made revision to read_data.R when log_pval=TRUE.

Thank you!

### CODE REVIEW

**Comment by explodecomputer** [comment]
This is brilliant thank you
Could I please ask that you make a pull request without the version bump? It seems to be causing CMD check to fail?

**Comment by remlapmot** [comment]
* To make edits to this PR - simply make additional edits on this branch and push them up to GitHub - they will appear below - no need for a new PR.

* As we're using roxygen it's better not to edit the `NAMESPACE` manually; rather add an additonal line
``` r
#' @export
```
before the `get_se <- ...` function definition in `query.R`; i.e. insert that as a new line at say line 200 in `query.R`.

Then, with top level of this repo as working directory in R, run `devtools::install_dev_deps()` to get the latest dependency packages then run `devtools::document()` to rebuild the NAMESPACE and helpfiles and push up to this branch on GitHub.

**Comment by jinghuazhao** [comment]
> 
> 
> This is brilliant thank you
> Could I please ask that you make a pull request without the version bump? It seems to be causing CMD check to fail?

**Comment by jinghuazhao** [comment]
I reversed the change to DESCRIPTION -- meant for our internal use really.

**Comment by remlapmot** [comment]
* @explodecomputer  - I hadn't noticed before - because we've used roxygen `#' ` prefix before the non-exported functions they all have helpfiles. This doesn't really worry me as users can just access with triple colon syntax - but is potentially confusing to novice R users - so we could add 
``` r
#' @keywords internal
```
to the unexported functions, which I believe would put their helpfiles on a single helpfile (I think which will be called internal).

**Comment by jinghuazhao** [comment]
Just followed those instructions -- I have been far less formal with these (e..g., (r)oxygen) so it is also a learning curve for me.

**Comment by remlapmot** [comment]
You need to push your local changes on the branch upto GitHub - as no new commits have appeared here

Also it best practice not to make the PR from your own master branch - because in a software project you should keep your master branch sync'd with the upstream master branch

**Comment by jinghuazhao** [comment]
maybe it is a bit of confusing -- I forked the repo again and made changes according to your earlier instructions and I have used 
git checkout -b jhz
git push --set-upstream origin jhz
Please let me know for additional issues.

**Comment by remlapmot** [comment]
Making the PR from your master branch has caused complications.

A PR tracks the original repo and branch it was sent from - as you've deleted it - we don't see the new commits here.

You've deleted your original fork because I assume you got a git merge error on your master branch this morning because Gib made a couple of commits into master after your PR.

So I suggest closing this PR and making a new PR - making sure that is not coming from your new fork's master branch - any other branch name will do. 

In general my original comment that you can edit a PR is correct - but it's essential that the PR is on a different branch, so you can easily rebase that branch if you end up needing to.

**Comment by jinghuazhao** [comment]
will try again.

**Pull request closed without merging**
